### PR TITLE
Fix index url installed packages (part 2)

### PR DESCRIPTION
**Pull request by janjaapdriessen**
I merged #18 to master. I tried to upload to pypi using zest.releaser, to find out I made a mistake in the setup.py metadata, which I tried to fix on master with a brown-paper-bag-release. I am not allowed to commit to master (for all the right reasons):

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access. 
```

I revived the branch and did the tag + upload to pypi from this branch. Would you please review these changes?

### CODE REVIEW

**Comment by mgedmin** [comment]
I've removed the branch protection because it totally breaks the `zest.releaser` workflow (which requires the person doing the upload to push the "release version X" and the "post-release version bump" commits directly to master).

**Comment by icemac** [comment]
@mgedmin At least I'd like to keep prevention of force pushes to `master` and deletion of the `master` branch provided by branch protection without any other requirements. Are you okay with this?

**Comment by mgedmin** [comment]
Yes, +:100: for disallowing forced pushes and deletion.

**Comment by mgedmin** [comment]
(Looks like I got confused by the UI and didn't realize that deleting the `master` protection rule would start allowing those actions.  I've now added it back, with no checkboxes checked, which matches the configuration of zope.interface.)

**Pull request merged**
